### ISSUE TITLE
CIG tester down for maintenance

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [geodynamics/Rayleigh#100]
Since the Jenkins tester has continued to have DNS issues, I'm planning on taking it offline to see if I can get it working. The plan is to take it down this week and get it back up next week. Please let me know if this will cause any issues.

**Comment by ljhwang** [comment]
Will this interfere with anyone’s AGU prep?

**Comment by feathern** [comment]
Is this resolved now?

**Comment by tjesser-ucdavis-edu** [comment]
Yes, the Jenkins server is now at https://jenkins.geodynamics.org. It is still configured to test Rayleigh pull requests.

**Comment by feathern** [comment]
Great thanks.  I thought it was probably back up since tests were passing again, but thought I would check to be sure.
