### ISSUE TITLE
Axial fields and turbulent KE equation codes missing from "Rayleigh Output Variables.pdf"

### ISSUE THREAD

**Issue by illorenzo7** [geodynamics/Rayleigh#118]
I am noticing just now that the quantities associated with the turbulent kinetic energy ("turbKE_codes.f") and axial field components ("axial_field_codes.F") do not appear in the Rayleigh documentation file, namely "Rayleigh Output Variables.pdf". Is this on purpose, because they are technically in the "custom codes" section? If not, I will go ahead and (try) to put them in the .tex file--additionally with a note that the custom diagnostics can be anywhere in between 2201 and 2700 (inclusive). 

Or, since there seem to be only ~20 turbKE codes, perhaps they could be included in the (regular) KE equation codes, which has room for about 40 more. And then perhaps the axial field codes could be distributed in the appropriate sections, leaving the space from 2201 onward blank for "true" custom codes. Though this might be more trouble than it's worth...

**Comment by orvedahl** [comment]
I'm not sure when it happened, but this has been fixed. The documentation now lives online and includes the turbulent KE terms as well as the axial field codes.
