### ISSUE TITLE
'--FFLAGS' option in configure deletes preprocessor flags

### ISSUE THREAD

**Issue by hirokemono** [geodynamics/Rayleigh#144]
When configure runs with '--FFLAGS' option, preprocessor flags by configure command (such as -DINTEL_COMPILER) disappears. Here is the example,

with --FFLAGS
login4(1048)$ ./configure --with-mkl=$(TACC_MKL_DIR) --FC=mpif90 --CC=icc --FFLAGS='-O3'
-bash: TACC_MKL_DIR: command not found

 -----------------------------------------------------------------------------
                          Rayleigh v0.9 Configuration
 -----------------------------------------------------------------------------

  Overriding all flags..,
 
 Compiler manufacturer      :  INTEL
 Fortran compiler command   :  mpif90
 Fortran optimization flags :  -O3
 Fortran debugging flags    :  -O3
 Intel compiler set:  MKLROOT is defined
 C compiler command         :  icc
 
***********************************************************************
 Intel compiler detected.  Please indicate desired SIMD instruction set.

 Suggested instruction sets are: 
 -- Westmere cores                  :  SSE4.2
 -- Sandy Bridge / Ivy Bridge cores :  AVX
 -- Haswell /Broadwell              :  AVX2 
 -- SkyLake / Knights Landing       :  AVX512 
 -- Support for all of the above    :  FAT

1) SSE4.2
2) AVX
3) AVX2
4) AVX512
5) ALL
6) FAT
7) NONE
#? 6
***********************************************************************
 Include flags              :  -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include/fftw

 Library flags              :  

 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Configuration is complete.
 A Machine_Definitions files has been placed in /home1/02179/matsui/Rayleigh/src/build.

 Typing 'make' will generate the following executables (optimization indicated): 
 rayleigh.opt  :   -O3 -xSSE4.2 -axAVX,CORE-AVX2,CORE-AVX512,MIC-AVX512
 rayleigh.dbg  :   -O3

==================================================================
no FFLAGS case
login4(1047)$ ./configure --with-mkl=$(TACC_MKL_DIR) --FC=mpif90 --CC=icc
-bash: TACC_MKL_DIR: command not found

 -----------------------------------------------------------------------------
                          Rayleigh v0.9 Configuration
 -----------------------------------------------------------------------------

 
 Compiler manufacturer      :  INTEL
 Fortran compiler command   :  mpif90
 Fortran optimization flags :  -FR -fpp -r8 -O3 -shared-intel -DINTEL_COMPILER
 Fortran debugging flags    :  -FR -fpp -r8 -O0 -g -CB -traceback -shared-intel -DINTEL_COMPILER
 Intel compiler set:  MKLROOT is defined
 C compiler command         :  icc
 
***********************************************************************
 Intel compiler detected.  Please indicate desired SIMD instruction set.

 Suggested instruction sets are: 
 -- Westmere cores                  :  SSE4.2
 -- Sandy Bridge / Ivy Bridge cores :  AVX
 -- Haswell /Broadwell              :  AVX2 
 -- SkyLake / Knights Landing       :  AVX512 
 -- Support for all of the above    :  FAT

1) SSE4.2
2) AVX
3) AVX2
4) AVX512
5) ALL
6) FAT
7) NONE
#? 6
***********************************************************************
 Include flags              :  -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include -I/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/include/fftw

 Library flags              :  

 
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Configuration is complete.
 A Machine_Definitions files has been placed in /home1/02179/matsui/Rayleigh/src/build.

 Typing 'make' will generate the following executables (optimization indicated): 
 rayleigh.opt  :   -FR -fpp -r8 -O3 -shared-intel -DINTEL_COMPILER -xSSE4.2 -axAVX,CORE-AVX2,CORE-AVX512,MIC-AVX512
 rayleigh.dbg  :   -FR -fpp -r8 -O0 -g -CB -traceback -shared-intel -DINTEL_COMPILER

**Comment by gassmoeller** [comment]
Should be fixed by #286.
