### ISSUE TITLE
Rayleigh Output Variables: Fix typos & tables

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/Rayleigh#22]
Fix typos in Rayleigh_Output_Variables. 

- [ ] 3.1 change "interpretted" to "interpreted" , 

- [ ] 3.2 change "...rotation rate of the grame, ..." to "... rotation rate of the frame, ..."

- [ ] tables have extra columns. Remove these.

**Comment by sglane9891** [comment]
- Tables should be arranged in a better way. Maybe we should use the longtable package.

- Page 4, second equation should be the Pm for magnetic Prandtl number.

Happy to go through this.

**Comment by sglane9891** [comment]
#42

**Comment by ljhwang** [comment]
I think these have been fixed.
