### ISSUE TITLE
Discuss how much Rayleigh checks input parameters for consistency

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/Rayleigh#26]
Most equation approximations (like Boussinesq, anelastic) assume a combination of existence / neglection of terms. Rayleigh currently checks some of these combinations, but not all of them. There are essentially three ways to handle this problem, but maybe we should settle on one consistent way as much as possible:
- do not check for consistency, easiest to implement
- do check, and automatically correct (add remove terms), might be confusing, but more comfortable
- do check, and crash with message if an inconsistency is detected, most explicit

Any opinion on what is most reasonable is appreciated.

**Comment by BWHindman** [comment]
I would prefer option 3.  If I screw up in specifying a parameter set, I don't want the code to ASSUME that I really meant to specify something else. Tell me where the inconsistency is, whimper, and then crash.

**Comment by gassmoeller** [comment]
Since this discussion is not something that can be definitely resolved, lets close the issue and keep the topic in mind for the future.
