### ISSUE TITLE
Acknowledgement file is mentioned in readme but does not exist

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/Rayleigh#27]
The correct filename is ACKNOWLEDGE. Properly link this in Readme.md (see https://guides.github.com/features/mastering-markdown/)

**Comment by ljhwang** [comment]
Is the ACKNOWLEDGE file standard practice?  I am wondering whether we should remove this file and distribute the content into a CITATION file (more common) with the remainder of the attribution information  in the README.md.
