### ISSUE TITLE
selecting native on mac using the conda environment gives a non-fatal error

### ISSUE THREAD

**Issue by cianwilson** [geodynamics/Rayleigh#302]
configure uses:
`gfortran -march=native -Q --help=target`
for gnu builds when native is selected at configure time.

Using the conda mac environment this results in:
```
fortran: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
```
which looks scary but the configuration actually carries on.

This appears to be caused by cc1 not being packaged by conda.  Anyone know of a workaround?

**Comment by gassmoeller** [comment]
I do not know of a fix. I saw this too on @ksoderlu Mac. I agree it seems to be an issue with the conda package.
