### ISSUE TITLE
Transition from Jenkins CI to Github actions

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/Rayleigh#322]
The CIG Jenkins server is down again, and we are thinking about simply transitioning the remaining projects to Github actions instead of putting more energy into repairing it again. Since Rayleigh already has Github actions that duplicate the tests of the Jenkins server, are you ok with me disabling the webhook to Jenkins? It would simply remove the little icon below every pull request that refers to the Jenkins server (we can also remove the Jenkinsfile in the repo at any point afterwards).

**Comment by tukss** [comment]
I'm in favor of that. I don't see a downside for us and it'll be less infrastructure for CIG to maintain.

**Comment by gassmoeller** [comment]
I have disabled the webhook for now. If you want it back it is a simple matter of clicking one check box, but for now this should remove the waiting for Jenkins symbol for every new PR. Eventually we can remove the Jenkinsfile from the repo, but that can happen at any point later.

**Comment by feathern** [comment]
Thanks Rene.  I'm going to close this issue.
