### ISSUE TITLE
Timestep and Rotation Rate

### ISSUE THREAD

**Issue by feathern** [geodynamics/Rayleigh#344]
The value of max_time_step should be adjusted at runtime if it exceeds the rotational timescale (1/{2 Omega} or Ekman/2).   In practice many of us set this value to be 5x smaller than the rotational timescale, but occasionally Rayleigh catches new users by surprise.  Note that this is necessary because the Coriolis terms are handled explicitly.   Were Rayleigh to handle them implicitly, the parallelization would not be as efficient.

**Comment by orvedahl** [comment]
This was addressed in PR #348
