### ISSUE TITLE
Documentation:  Jupyter notebook python output

### ISSUE THREAD

**Issue by feathern** [geodynamics/Rayleigh#353]
There are several places in the documentation where the build process is attempting to run Python code that relies on nonexistent files (on the documentation server).  These are typically cells that illustrate plotting examples.  It would be good to adjust this so that the python code is displayed, but not executed, so that the documentation does not appear broken in places.

A prime example can be seen [here](https://rayleigh-documentation.readthedocs.io/en/latest/post_processing/Diagnostic_Plotting.html#II.-Configuring-Your-Python-Environment).

**Comment by gassmoeller** [comment]
Some documentation about how to exclude notebooks from running in sphinx: https://nbsphinx.readthedocs.io/en/0.8.8/never-execute.html
