### ISSUE TITLE
Reading Failure a series of global average data files with different sizes (self.niter)

### ISSUE THREAD

**Issue by hirokemono** [geodynamics/Rayleigh#375]
The Global average data reading class (G_Avgs in Rayleigh_diagnostics.py), the size of data array "gavgs" seems to be defined by using the number of steps in one data file self.niter in the first global average data file. However, the the data series in INCITE data has a different size of self.niter, and program plot_G_Avegs.py crushes. The data array to read would be defined when reading each data file as the old version.

File to be read:  G_Avgs/06560000
self.version, self.niter, self.nq: 3 100 14
File to be read:  G_Avgs/06570000
self.version, self.niter, self.nq: 3 41 14
Traceback (most recent call last):
  File "/Volumes/pub_s/INCITE_summary/ryadav/ensemble2/Pm0.1_Pr1_eta0.35_Ek1E-6_Ra1E10_no-slip_dyn/plot_G_Avgs.py", line 112, in <module>
    gavgs[i0:i1,:] = a.vals
ValueError: could not broadcast input array from shape (41,14) into shape (100,14)

**Comment by tukss** [comment]
The new Python interface in `rayleigh.py` merged in #274 doesn't have this issue. Still it might be nice to fix it in the old scripts.
