### ISSUE TITLE
Documentation doesn't seem to be updating

### ISSUE THREAD

**Issue by nicholasjnelson** [geodynamics/Rayleigh#409]
Last week I made several pull requests that modified the "3-D Visualization with VAPOR" section of the "Analyzing Output" past of the User Guide, however the online documentation doesn't seem to be showing the updates. The online version is not consistent with the current contents of the source code. Any ideas why?

**Comment by feathern** [comment]
I tried to use the 'edit' feature on the 3-D vis page.   I received 404:
https://github.com/geodynamics/rayleigh/edit/master/doc/source/User_Guide/analyze_output.rst
It looks like it's trying to pull from the master branch.  I *think* just updated the settings to use 'main' for the readthedocs 'latest' version.   We will see in a bit.
-Nick

**Comment by feathern** [comment]
I think that fixed it!
