### ISSUE TITLE
Possible bug in rayleigh_diagnostics

### ISSUE THREAD

**Issue by illorenzo7** [geodynamics/Rayleigh#91]
I believe there is a bug in the Shell_Slices class in rayleigh_diagnostics. On line 736, the statement

self.lut = get_lut(self.qv)

leads to an error, because self.qv has not been set yet (only qv). 

2 possible solutions:

1. change self.qv --> qv in line 736
2. move line 736 to somewhere after line 831, when self.qv is actually set. It looks the statement self.lut = get_lut(self.qv) got moved to line 736 from somewhere else for some particular reason (given all the empty space surrounding it), so I am hesitant to make a pull request until knowing why this happened.

**Comment by orvedahl** [comment]
I'm pretty sure this was a result of my pull request. It is definitely a bug and the better solution is to simply change self.qv --> qv. I found another related bug that I missed before. Both bugs should be addressed in a pull request that will be posted in just a minute.

**Comment by gassmoeller** [comment]
Is this closed by #91?

**Comment by orvedahl** [comment]
@gassmoeller, yes this issue was addressed by that merge and should be closed.
